// -----------------------------------------------------------------------------
// SQLite database layer.
//
// Schema:
//
//   factories  — one row per known DEX factory, per chain
//     (we also store name/type/fee here for reference; source of truth is config)
//
//   pairs      — one row per V2 pair, discovered via PairCreated events
//     UNIQUE(factory, address) prevents duplicate inserts on rescan
//     Indexed by token0, token1, and (token0, token1) for triangle enumeration
//
//   reserves   — rolling snapshot of pair reserves (one row per pair, upserted)
//     reserves0/1 stored as TEXT because uint112 can exceed JS Number precision
//     when tokens have 18 decimals and pool holds > ~9M tokens
//
//   scan_progress — last block scanned per factory, so we can resume
//
// -----------------------------------------------------------------------------

import Database from 'better-sqlite3';
import type { Database as DB } from 'better-sqlite3';

const SCHEMA = `
    CREATE TABLE IF NOT EXISTS factories (
        address     TEXT PRIMARY KEY,
        name        TEXT NOT NULL,
        type        TEXT NOT NULL DEFAULT 'v2',
        -- Nullable: v2/v3 have a flat fee (0.003 default); v2fee/solidly can
        -- either declare a flat fee (opt-in flat-fee mode) OR leave it NULL
        -- to signal per-pair lookup via feeFunction. NULL means "see the
        -- factory config's feeTarget/feeFunction/feeDivisor and pairs.fee".
        fee         REAL,
        deployBlock INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS pairs (
        address     TEXT NOT NULL,
        factory     TEXT NOT NULL,
        token0      TEXT NOT NULL,
        token1      TEXT NOT NULL,
        blockNumber INTEGER NOT NULL,
        -- Nullable per-pair overrides for Solidly-family factories where
        -- fee varies per pair (looked up via factory.pairFee(pair)) and
        -- pairs have distinct stable vs volatile curves.
        -- NULL = use factory-level defaults; only V2/V3 assumptions apply.
        fee         REAL,
        stable      INTEGER,  -- 0/1, NULL for pure V2 (no stable/volatile distinction)
        PRIMARY KEY (factory, address)
    );

    -- Indexes for triangle enumeration: "give me pairs containing token X"
    CREATE INDEX IF NOT EXISTS idx_pairs_token0 ON pairs(token0);
    CREATE INDEX IF NOT EXISTS idx_pairs_token1 ON pairs(token1);
    CREATE INDEX IF NOT EXISTS idx_pairs_tokens ON pairs(token0, token1);
    CREATE INDEX IF NOT EXISTS idx_pairs_factory ON pairs(factory);

    CREATE TABLE IF NOT EXISTS reserves (
        pair        TEXT PRIMARY KEY,
        reserves0   TEXT NOT NULL,
        reserves1   TEXT NOT NULL,
        blockNumber INTEGER NOT NULL,
        updatedAt   INTEGER NOT NULL   -- unix timestamp
    );

    CREATE INDEX IF NOT EXISTS idx_reserves_block ON reserves(blockNumber);

    CREATE TABLE IF NOT EXISTS scan_progress (
        factory      TEXT PRIMARY KEY,
        lastBlock    INTEGER NOT NULL,
        updatedAt    INTEGER NOT NULL
    );

    -- Triangles: cached enumeration of arb cycles rooted at flash-loanable tokens.
    -- Regenerated by \`yarn triangles <chain>\` after significant pair changes.
    -- The evaluator (piece 5) reads this table + reserves to score each triangle.
    CREATE TABLE IF NOT EXISTS triangles (
        id           INTEGER PRIMARY KEY,
        root_token   TEXT NOT NULL,   -- the flash-loan token; cycle starts and ends here
        hop_count    INTEGER NOT NULL,  -- 2 or 3

        -- Tokens in cycle order (a → b → c → a)
        -- For hop_count=2, token_c = token_a = root_token
        token_a      TEXT NOT NULL,
        token_b      TEXT NOT NULL,
        token_c      TEXT NOT NULL,

        -- Pairs used at each hop
        pair_ab      TEXT NOT NULL,
        pair_bc      TEXT NOT NULL,
        pair_ca      TEXT NOT NULL,

        -- Factories used at each hop (for filtering: same-factory triangles have no arb)
        factory_ab   TEXT NOT NULL,
        factory_bc   TEXT NOT NULL,
        factory_ca   TEXT NOT NULL,

        -- Canonical dedup key: rotation-invariant string built from sorted pair addresses.
        -- Uniqueness enforced via idx_triangles_canonical below (an explicit,
        -- named index), NOT an inline UNIQUE column constraint — inline UNIQUE
        -- creates an internal sqlite_autoindex that can't be dropped/rebuilt by
        -- name, which blocks the bulk-insert optimization (drop indexes, insert
        -- millions of rows, rebuild indexes in one sorted pass) used for large
        -- chains. See insertTriangles() and migrateTrianglesCanonicalIndex().
        canonical    TEXT NOT NULL,

        createdAt    INTEGER NOT NULL
    );

    CREATE UNIQUE INDEX IF NOT EXISTS idx_triangles_canonical ON triangles(canonical);
    CREATE INDEX IF NOT EXISTS idx_triangles_root ON triangles(root_token);
    CREATE INDEX IF NOT EXISTS idx_triangles_hop  ON triangles(hop_count);
    CREATE INDEX IF NOT EXISTS idx_triangles_pair_ab ON triangles(pair_ab);
    CREATE INDEX IF NOT EXISTS idx_triangles_pair_bc ON triangles(pair_bc);
    CREATE INDEX IF NOT EXISTS idx_triangles_pair_ca ON triangles(pair_ca);

    -- Token metadata (symbol / name / decimals) fetched from the chain.
    -- Populated by \`yarn tokens <chain>\`. Read-side JOINed by any UI or log
    -- output that wants to show token addresses as human-readable symbols.
    --
    -- \`fetchStatus\`: 'ok' when the on-chain fetch succeeded;
    --                 'reverted' when the token's symbol()/decimals() reverted
    --                            (non-standard ERC20; symbol/decimals will be NULL);
    --                 'nocode' when the address has no bytecode (long-tail
    --                          scam contracts get self-destructed);
    --                 'pending' when we've seen the address but not yet fetched.
    CREATE TABLE IF NOT EXISTS tokens (
        address      TEXT PRIMARY KEY,
        symbol       TEXT,
        name         TEXT,
        decimals     INTEGER,
        fetchStatus  TEXT NOT NULL,   -- 'ok' | 'reverted' | 'nocode' | 'pending'
        fetchedAt    INTEGER,          -- unix ts
        discoveredAt INTEGER NOT NULL  -- unix ts of first-seen
    );

    CREATE INDEX IF NOT EXISTS idx_tokens_symbol ON tokens(symbol);
    CREATE INDEX IF NOT EXISTS idx_tokens_status ON tokens(fetchStatus);
`;

/**
 * Schema migration: for existing databases that don't have the fee/stable
 * columns on pairs, add them. ALTER TABLE ADD COLUMN is idempotent-safe if
 * we check first.
 */
function migratePairsColumns(db: import('better-sqlite3').Database): void {
    const cols = db.prepare("PRAGMA table_info(pairs)").all() as Array<{ name: string }>;
    const names = new Set(cols.map(c => c.name));
    if (!names.has('fee')) {
        db.exec('ALTER TABLE pairs ADD COLUMN fee REAL');
    }
    if (!names.has('stable')) {
        db.exec('ALTER TABLE pairs ADD COLUMN stable INTEGER');
    }
}

/**
 * Schema migration: factories.fee was originally NOT NULL DEFAULT 0.003, but
 * v2fee/solidly factories legitimately have NULL fees (per-pair mode). SQLite
 * can't ALTER COLUMN DROP NOT NULL, so we swap the table: create a new one
 * with the correct schema, copy data over, drop old, rename.
 *
 * Idempotent: checks PRAGMA table_info's `notnull` flag first. If the fee
 * column is already nullable, does nothing.
 */
function migrateFactoriesFeeNullable(db: import('better-sqlite3').Database): void {
    const cols = db.prepare("PRAGMA table_info(factories)").all() as Array<{ name: string; notnull: number }>;
    const feeCol = cols.find(c => c.name === 'fee');
    // notnull is 0 for nullable, non-zero for NOT NULL. If missing or already nullable, skip.
    if (!feeCol || feeCol.notnull === 0) return;

    db.exec(`
        BEGIN;
        CREATE TABLE factories_new (
            address     TEXT PRIMARY KEY,
            name        TEXT NOT NULL,
            type        TEXT NOT NULL DEFAULT 'v2',
            fee         REAL,
            deployBlock INTEGER NOT NULL
        );
        INSERT INTO factories_new (address, name, type, fee, deployBlock)
            SELECT address, name, type, fee, deployBlock FROM factories;
        DROP TABLE factories;
        ALTER TABLE factories_new RENAME TO factories;
        COMMIT;
    `);
}

/**
 * Schema migration: triangles.canonical was originally an inline UNIQUE
 * column constraint, which SQLite backs with an internal sqlite_autoindex_*
 * that can't be dropped/recreated by name. That blocks the bulk-insert
 * optimization (drop all indexes before a huge insert, rebuild them in one
 * sorted pass after — far faster than maintaining 6 B-trees incrementally
 * across millions of individual row inserts, which is what made triangle
 * persistence slow on large chains like Polygon).
 *
 * Migrates by table-swap (SQLite can't drop an inline constraint via ALTER),
 * same pattern as migrateFactoriesFeeNullable. Idempotent: detects the old
 * inline UNIQUE via PRAGMA index_list's autoindex naming and no-ops if
 * already migrated (or if the table doesn't exist yet — SCHEMA above already
 * creates the new shape for a fresh DB).
 */
function migrateTrianglesCanonicalIndex(db: import('better-sqlite3').Database): void {
    const tableExists = db.prepare(
        `SELECT name FROM sqlite_master WHERE type='table' AND name='triangles'`
    ).get();
    if (!tableExists) return;

    const indexes = db.prepare(`PRAGMA index_list(triangles)`).all() as Array<{ name: string; unique: number; origin: string }>;
    const hasInlineUnique = indexes.some(idx => idx.origin === 'u' && idx.name.startsWith('sqlite_autoindex_triangles_'));
    if (!hasInlineUnique) return;

    db.exec(`
        BEGIN;
        CREATE TABLE triangles_new (
            id           INTEGER PRIMARY KEY,
            root_token   TEXT NOT NULL,
            hop_count    INTEGER NOT NULL,
            token_a      TEXT NOT NULL,
            token_b      TEXT NOT NULL,
            token_c      TEXT NOT NULL,
            pair_ab      TEXT NOT NULL,
            pair_bc      TEXT NOT NULL,
            pair_ca      TEXT NOT NULL,
            factory_ab   TEXT NOT NULL,
            factory_bc   TEXT NOT NULL,
            factory_ca   TEXT NOT NULL,
            canonical    TEXT NOT NULL,
            createdAt    INTEGER NOT NULL
        );
        INSERT INTO triangles_new SELECT
            id, root_token, hop_count, token_a, token_b, token_c,
            pair_ab, pair_bc, pair_ca, factory_ab, factory_bc, factory_ca,
            canonical, createdAt
        FROM triangles;
        DROP TABLE triangles;
        ALTER TABLE triangles_new RENAME TO triangles;
        CREATE UNIQUE INDEX IF NOT EXISTS idx_triangles_canonical ON triangles(canonical);
        CREATE INDEX IF NOT EXISTS idx_triangles_root ON triangles(root_token);
        CREATE INDEX IF NOT EXISTS idx_triangles_hop  ON triangles(hop_count);
        CREATE INDEX IF NOT EXISTS idx_triangles_pair_ab ON triangles(pair_ab);
        CREATE INDEX IF NOT EXISTS idx_triangles_pair_bc ON triangles(pair_bc);
        CREATE INDEX IF NOT EXISTS idx_triangles_pair_ca ON triangles(pair_ca);
        COMMIT;
    `);
}

// -----------------------------------------------------------------------------

export type PairRow = {
    address: string;
    factory: string;
    token0: string;
    token1: string;
    blockNumber: number;
    // Solidly-family only; NULL for pure V2 pairs.
    fee?: number | null;
    stable?: boolean | null;
};

export type ReserveRow = {
    pair: string;
    reserves0: string;   // decimal string, parse to BigInt
    reserves1: string;
    blockNumber: number;
    updatedAt: number;
};

// -----------------------------------------------------------------------------

export class ArbitradeDB {
    readonly db: DB;

    constructor(filePath: string) {
        this.db = new Database(filePath);
        this.db.pragma('journal_mode = WAL');   // better concurrency
        this.db.pragma('synchronous = NORMAL'); // ~2x write speedup, still safe
        this.db.exec(SCHEMA);
        migratePairsColumns(this.db);
        migrateFactoriesFeeNullable(this.db);
        migrateTrianglesCanonicalIndex(this.db);
    }

    close() {
        this.db.close();
    }

    // ------------------------------------------- factories

    upsertFactory(f: { address: string; name: string; type: string; fee: number | null | undefined; deployBlock: number }) {
        this.db.prepare(`
            INSERT INTO factories (address, name, type, fee, deployBlock)
            VALUES (@address, @name, @type, @fee, @deployBlock)
            ON CONFLICT(address) DO UPDATE SET
                name        = excluded.name,
                type        = excluded.type,
                fee         = excluded.fee,
                deployBlock = excluded.deployBlock
        `).run({
            address: f.address.toLowerCase(),
            name: f.name,
            type: f.type,
            // Normalize undefined → null so better-sqlite3's parameter binding
            // treats it as SQL NULL rather than throwing.
            fee: f.fee ?? null,
            deployBlock: f.deployBlock,
        });
    }

    /** Fetch the cached deploy block for a factory, or null if unknown. */
    getFactoryDeployBlock(address: string): number | null {
        const row = this.db.prepare('SELECT deployBlock FROM factories WHERE address = ?')
            .get(address.toLowerCase()) as { deployBlock: number } | undefined;
        // Zero means "not yet discovered" — same as absent
        if (!row || !row.deployBlock) return null;
        return row.deployBlock;
    }

    // ------------------------------------------- pairs

    /**
     * Insert a batch of pairs in one transaction. Returns count inserted
     * (duplicates via UNIQUE(factory, address) are silently ignored).
     */
    insertPairs(rows: PairRow[]): number {
        const stmt = this.db.prepare(`
            INSERT OR IGNORE INTO pairs (address, factory, token0, token1, blockNumber, fee, stable)
            VALUES (@address, @factory, @token0, @token1, @blockNumber, @fee, @stable)
        `);
        const tx = this.db.transaction((rs: PairRow[]) => {
            let n = 0;
            for (const r of rs) {
                const res = stmt.run({
                    address: r.address.toLowerCase(),
                    factory: r.factory.toLowerCase(),
                    token0: r.token0.toLowerCase(),
                    token1: r.token1.toLowerCase(),
                    blockNumber: r.blockNumber,
                    fee: r.fee ?? null,
                    stable: r.stable == null ? null : (r.stable ? 1 : 0),
                });
                if (res.changes > 0) n++;
            }
            return n;
        });
        return tx(rows);
    }

    countPairs(factory?: string): number {
        if (factory) {
            const row = this.db.prepare('SELECT COUNT(*) AS n FROM pairs WHERE factory = ?')
                .get(factory.toLowerCase()) as { n: number };
            return row.n;
        }
        const row = this.db.prepare('SELECT COUNT(*) AS n FROM pairs').get() as { n: number };
        return row.n;
    }

    // ------------------------------------------- token metadata

    /**
     * Return all distinct token addresses referenced by any pair (or by
     * pairs matching optional filters). Used by \`yarn tokens\` to discover
     * what to fetch metadata for.
     *
     * `withReservesOnly`: if true, only tokens whose pairs have at least one
     * non-zero-reserve pool. Cuts the working set roughly in half on Polygon
     * (skips tokens that only appear in dead scaffold pairs).
     *
     * `unfetchedOnly`: skip tokens already in the tokens table with a
     * terminal fetchStatus ('ok', 'reverted', 'nocode'). Default true.
     */
    listPairTokens(opts: { withReservesOnly?: boolean; unfetchedOnly?: boolean } = {}): string[] {
        const withReserves = opts.withReservesOnly ?? false;
        const unfetched = opts.unfetchedOnly ?? true;

        // Build one query that unions token0/token1 across pairs, optionally
        // gated by "has any non-zero reserves ever", and optionally excludes
        // addresses already in tokens table.
        const pairFilter = withReserves
            ? `WHERE address IN (SELECT DISTINCT pair FROM reserves WHERE reserves0 > 0 OR reserves1 > 0)`
            : '';
        const query = `
            WITH pair_tokens AS (
                SELECT token0 AS address FROM pairs ${pairFilter}
                UNION
                SELECT token1 AS address FROM pairs ${pairFilter}
            )
            SELECT DISTINCT address FROM pair_tokens
            ${unfetched
                ? `WHERE address NOT IN (SELECT address FROM tokens WHERE fetchStatus IN ('ok', 'reverted', 'nocode'))`
                : ''}
        `;
        return (this.db.prepare(query).all() as Array<{ address: string }>).map(r => r.address);
    }

    /**
     * Upsert a batch of token metadata rows. Existing rows are updated;
     * discoveredAt is preserved.
     */
    upsertTokens(rows: Array<{
        address: string;
        symbol: string | null;
        name: string | null;
        decimals: number | null;
        fetchStatus: 'ok' | 'reverted' | 'nocode' | 'pending';
    }>): number {
        if (rows.length === 0) return 0;
        const now = Math.floor(Date.now() / 1000);
        const stmt = this.db.prepare(`
            INSERT INTO tokens (address, symbol, name, decimals, fetchStatus, fetchedAt, discoveredAt)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(address) DO UPDATE SET
                symbol = excluded.symbol,
                name = excluded.name,
                decimals = excluded.decimals,
                fetchStatus = excluded.fetchStatus,
                fetchedAt = excluded.fetchedAt
        `);
        const tx = this.db.transaction((batch: typeof rows) => {
            let n = 0;
            for (const r of batch) {
                stmt.run(r.address.toLowerCase(), r.symbol, r.name, r.decimals, r.fetchStatus, now, now);
                n++;
            }
            return n;
        });
        return tx(rows);
    }

    /**
     * Fetch known token metadata for a set of addresses. Returns a map keyed
     * by lowercased address. Missing addresses simply aren't in the returned
     * map. Used by display code (evaluator output, discovery.json) to swap
     * addresses for symbols.
     */
    getTokens(addresses: string[]): Map<string, { address: string; symbol: string | null; name: string | null; decimals: number | null; fetchStatus: string }> {
        const out = new Map();
        if (addresses.length === 0) return out;
        const lower = addresses.map(a => a.toLowerCase());
        // SQLite has a parameter limit (~999). Chunk defensively.
        const CHUNK = 500;
        for (let i = 0; i < lower.length; i += CHUNK) {
            const chunk = lower.slice(i, i + CHUNK);
            const placeholders = chunk.map(() => '?').join(',');
            const rows = this.db.prepare(
                `SELECT address, symbol, name, decimals, fetchStatus FROM tokens WHERE address IN (${placeholders})`
            ).all(...chunk) as Array<{ address: string; symbol: string | null; name: string | null; decimals: number | null; fetchStatus: string }>;
            for (const r of rows) out.set(r.address, r);
        }
        return out;
    }

    tokenStats(): { total: number; ok: number; reverted: number; nocode: number; pending: number } {
        const rows = this.db.prepare(
            `SELECT fetchStatus, COUNT(*) AS n FROM tokens GROUP BY fetchStatus`
        ).all() as Array<{ fetchStatus: string; n: number }>;
        const out = { total: 0, ok: 0, reverted: 0, nocode: 0, pending: 0 };
        for (const r of rows) {
            out.total += r.n;
            (out as any)[r.fetchStatus] = r.n;
        }
        return out;
    }

    // ------------------------------------------- scan progress

    getScanProgress(factory: string): number | null {
        const row = this.db.prepare('SELECT lastBlock FROM scan_progress WHERE factory = ?')
            .get(factory.toLowerCase()) as { lastBlock: number } | undefined;
        return row?.lastBlock ?? null;
    }

    setScanProgress(factory: string, block: number) {
        this.db.prepare(`
            INSERT INTO scan_progress (factory, lastBlock, updatedAt)
            VALUES (?, ?, ?)
            ON CONFLICT(factory) DO UPDATE SET
                lastBlock = excluded.lastBlock,
                updatedAt = excluded.updatedAt
        `).run(factory.toLowerCase(), block, Math.floor(Date.now() / 1000));
    }

    // ------------------------------------------- reserves

    /**
     * Get pairs that need a reserves refresh. Optionally filter by:
     *   - factory: only pairs from this factory
     *   - maxAgeSeconds: skip pairs whose reserves were updated more recently
     *
     * Returns an array in the shape the fetcher wants (with the pair's factory
     * so the caller can group by group/family).
     */
    getPairsForReservesFetch(opts: {
        factory?: string;
        maxAgeSeconds?: number;
        /** If set, only return pairs whose factory is in this allowlist (lowercase). */
        factoryAllowlist?: string[];
    } = {}): Array<{ pair: string; factory: string; token0: string; token1: string }> {
        const wheres: string[] = [];
        const params: any[] = [];
        if (opts.factory) {
            wheres.push('p.factory = ?');
            params.push(opts.factory.toLowerCase());
        }
        if (opts.factoryAllowlist && opts.factoryAllowlist.length > 0) {
            const placeholders = opts.factoryAllowlist.map(() => '?').join(',');
            wheres.push(`p.factory IN (${placeholders})`);
            params.push(...opts.factoryAllowlist.map(a => a.toLowerCase()));
        }
        if (opts.maxAgeSeconds !== undefined) {
            const cutoff = Math.floor(Date.now() / 1000) - opts.maxAgeSeconds;
            // "r.updatedAt is null" means we've never fetched reserves for this pair yet
            wheres.push('(r.updatedAt IS NULL OR r.updatedAt < ?)');
            params.push(cutoff);
        }
        const where = wheres.length ? 'WHERE ' + wheres.join(' AND ') : '';
        return this.db.prepare(`
            SELECT p.address AS pair, p.factory, p.token0, p.token1
            FROM pairs p
            LEFT JOIN reserves r ON r.pair = p.address
            ${where}
            ORDER BY p.factory, p.address
        `).all(...params) as any;
    }

    /**
     * Count pairs whose factory is NOT in the provided allowlist. Useful for
     * detecting orphan pairs left behind by prior scans of factories that
     * have since been removed from the config.
     */
    countOrphanPairs(currentFactories: string[]): Array<{ factory: string; count: number }> {
        const allowlist = currentFactories.map(a => a.toLowerCase());
        const placeholders = allowlist.map(() => '?').join(',');
        const where = allowlist.length > 0
            ? `WHERE factory NOT IN (${placeholders})`
            : '';
        return this.db.prepare(`
            SELECT factory, COUNT(*) AS count
            FROM pairs
            ${where}
            GROUP BY factory
            ORDER BY count DESC
        `).all(...allowlist) as any;
    }

    /**
     * Delete pairs (and their reserves rows) whose factory is not in the
     * allowlist. Returns the number of pairs deleted.
     */
    deleteOrphanPairs(currentFactories: string[]): number {
        const allowlist = currentFactories.map(a => a.toLowerCase());
        const placeholders = allowlist.map(() => '?').join(',');
        const clause = allowlist.length > 0
            ? `WHERE factory NOT IN (${placeholders})`
            : '';
        const tx = this.db.transaction(() => {
            // First reserves rows referencing to-be-deleted pairs
            this.db.prepare(`
                DELETE FROM reserves
                WHERE pair IN (SELECT address FROM pairs ${clause})
            `).run(...allowlist);
            const info = this.db.prepare(`DELETE FROM pairs ${clause}`).run(...allowlist);
            return info.changes;
        });
        return tx();
    }

    /**
     * Upsert reserves for a batch of pairs. Zero-reserve pairs should be
     * filtered out by the caller (we don't waste space on dead pools).
     */
    upsertReserves(rows: Array<{
        pair: string;
        reserves0: bigint;
        reserves1: bigint;
        blockNumber: number;
    }>): number {
        const now = Math.floor(Date.now() / 1000);
        const stmt = this.db.prepare(`
            INSERT INTO reserves (pair, reserves0, reserves1, blockNumber, updatedAt)
            VALUES (@pair, @reserves0, @reserves1, @blockNumber, @updatedAt)
            ON CONFLICT(pair) DO UPDATE SET
                reserves0   = excluded.reserves0,
                reserves1   = excluded.reserves1,
                blockNumber = excluded.blockNumber,
                updatedAt   = excluded.updatedAt
        `);
        const tx = this.db.transaction((rs: typeof rows) => {
            let n = 0;
            for (const r of rs) {
                const res = stmt.run({
                    pair:      r.pair.toLowerCase(),
                    reserves0: r.reserves0.toString(),   // TEXT column, decimal string
                    reserves1: r.reserves1.toString(),
                    blockNumber: r.blockNumber,
                    updatedAt: now,
                });
                if (res.changes > 0) n++;
            }
            return n;
        });
        return tx(rows);
    }

    countReserves(): number {
        const row = this.db.prepare('SELECT COUNT(*) AS n FROM reserves').get() as { n: number };
        return row.n;
    }

    // ------------------------------------------- pair metadata (fee/stable for solidly-family)

    /**
     * Get pairs from a specific factory that lack fee/stable metadata.
     * If `forceRefresh` is true, returns ALL pairs regardless of whether
     * metadata is already populated (for the periodic refresh command).
     */
    getPairsForMetadataFetch(factory: string, forceRefresh: boolean): Array<{ pair: string; stable: number | null }> {
        const where = forceRefresh
            ? 'factory = ?'
            : 'factory = ? AND fee IS NULL';
        return this.db.prepare(`
            SELECT address AS pair, stable
            FROM pairs
            WHERE ${where}
            ORDER BY address
        `).all(factory.toLowerCase()) as any;
    }

    /** Update fee (and stable, if provided) for a single pair. */
    updatePairMetadata(rows: Array<{ pair: string; fee: number; stable?: boolean | null }>): number {
        const stmt = this.db.prepare(`
            UPDATE pairs
            SET fee = @fee,
                stable = COALESCE(@stable, stable)
            WHERE address = @pair
        `);
        const tx = this.db.transaction((rs: typeof rows) => {
            let n = 0;
            for (const r of rs) {
                const res = stmt.run({
                    pair:   r.pair.toLowerCase(),
                    fee:    r.fee,
                    stable: r.stable == null ? null : (r.stable ? 1 : 0),
                });
                if (res.changes > 0) n++;
            }
            return n;
        });
        return tx(rows);
    }

    // ------------------------------------------- orchestrator (piece 6) lookups

    /**
     * Look up token0/token1 for a batch of pair addresses. Used by the
     * orchestrator's hop builder to decide which side of a pair's swap()
     * call gets the nonzero amountOut, without an extra on-chain call —
     * token0/token1 ordering is fixed at pair creation and already cached
     * from the scan.
     */
    getPairTokenOrder(addresses: string[]): Map<string, { token0: string; token1: string }> {
        const out = new Map<string, { token0: string; token1: string }>();
        if (addresses.length === 0) return out;
        const lower = [...new Set(addresses.map(a => a.toLowerCase()))];
        const CHUNK = 500;
        for (let i = 0; i < lower.length; i += CHUNK) {
            const chunk = lower.slice(i, i + CHUNK);
            const placeholders = chunk.map(() => '?').join(',');
            const rows = this.db.prepare(
                `SELECT address, token0, token1 FROM pairs WHERE address IN (${placeholders})`
            ).all(...chunk) as Array<{ address: string; token0: string; token1: string }>;
            for (const r of rows) out.set(r.address, { token0: r.token0, token1: r.token1 });
        }
        return out;
    }

    /**
     * One pair address for a given factory, for callers that just need a
     * representative sample (e.g. bytecode-based fee derivation) rather than
     * the full pair list. Picks deterministically (lowest address) so repeat
     * calls are stable. Returns null if the factory has no scanned pairs.
     */
    getSamplePairForFactory(factory: string): { pair: string; token0: string; token1: string } | null {
        const row = this.db.prepare(
            `SELECT address AS pair, token0, token1 FROM pairs WHERE factory = ? ORDER BY address LIMIT 1`
        ).get(factory.toLowerCase()) as { pair: string; token0: string; token1: string } | undefined;
        return row ?? null;
    }

    // ------------------------------------------- triangle enumeration inputs

    /**
     * Load every pair with a live non-zero reserve, joined with its factory
     * and current fee/stable. Returned as a flat array — the enumerator
     * builds its own indexes from this. Excludes zero-reserve pairs (no arb
     * point) and stable pools by default (constant-product math is wrong for
     * them; separate stable-swap support is future work).
     */
    getPairsForEnumeration(opts: { includeStable?: boolean } = {}): Array<{
        pair:        string;
        factory:     string;
        token0:      string;
        token1:      string;
        fee:         number | null;   // per-pair for v2fee/solidly; NULL for pure v2
        stable:      number | null;   // 0/1 or NULL
    }> {
        const includeStable = opts.includeStable ?? false;
        const stableClause = includeStable ? '' : 'AND (p.stable IS NULL OR p.stable = 0)';
        return this.db.prepare(`
            SELECT p.address AS pair, p.factory, p.token0, p.token1, p.fee, p.stable
            FROM pairs p
            INNER JOIN reserves r ON r.pair = p.address
            WHERE r.reserves0 != '0' AND r.reserves1 != '0'
            ${stableClause}
            ORDER BY p.address
        `).all() as any;
    }

    // ------------------------------------------- triangles

    /**
     * Drop all triangles for regeneration. The evaluator doesn't hold long-term
     * state on triangles, so blowing the table away and rebuilding is cheap.
     */
    clearTriangles(): number {
        const info = this.db.prepare('DELETE FROM triangles').run();
        return info.changes;
    }

    clearTrianglesByRoot(rootToken: string): number {
        const info = this.db.prepare('DELETE FROM triangles WHERE root_token = ?')
            .run(rootToken.toLowerCase());
        return info.changes;
    }

    countTriangles(): { total: number; byHop: Record<number, number>; byRoot: Record<string, number> } {
        const total = (this.db.prepare('SELECT COUNT(*) AS n FROM triangles').get() as any).n;
        const byHopRows = this.db.prepare('SELECT hop_count, COUNT(*) AS n FROM triangles GROUP BY hop_count').all() as any[];
        const byRootRows = this.db.prepare('SELECT root_token, COUNT(*) AS n FROM triangles GROUP BY root_token').all() as any[];
        const byHop: Record<number, number> = {};
        for (const r of byHopRows) byHop[r.hop_count] = r.n;
        const byRoot: Record<string, number> = {};
        for (const r of byRootRows) byRoot[r.root_token] = r.n;
        return { total, byHop, byRoot };
    }

    /**
     * Drop the triangles table's 5 SECONDARY indexes (root/hop/pair_ab/bc/ca).
     * Deliberately does NOT drop idx_triangles_canonical — that's the
     * uniqueness constraint that makes INSERT OR IGNORE correctly de-dupe
     * both within a batch AND against pre-existing rows left by a --root
     * partial run. The same physical triangle can legitimately be reachable
     * from more than one flash-loan root (canonical is built from sorted pair
     * addresses only, not the root token), so cross-root canonical collisions
     * are a real, expected case — dropping the uniqueness index would let
     * duplicates land silently and then crash the index rebuild afterward.
     * Used around bulk inserts — see insertTriangles().
     */
    dropTriangleIndexes(): void {
        this.db.exec(`
            DROP INDEX IF EXISTS idx_triangles_root;
            DROP INDEX IF EXISTS idx_triangles_hop;
            DROP INDEX IF EXISTS idx_triangles_pair_ab;
            DROP INDEX IF EXISTS idx_triangles_pair_bc;
            DROP INDEX IF EXISTS idx_triangles_pair_ca;
        `);
    }

    /**
     * Recreate the triangles table's 5 secondary indexes. SQLite builds a
     * fresh index on a populated table via a single sorted pass —
     * dramatically faster than the incremental B-tree updates that happen on
     * every row during a plain INSERT loop, which is what makes this
     * drop/insert/rebuild pattern worthwhile for millions of rows.
     */
    createTriangleIndexes(): void {
        this.db.exec(`
            CREATE INDEX IF NOT EXISTS idx_triangles_root ON triangles(root_token);
            CREATE INDEX IF NOT EXISTS idx_triangles_hop  ON triangles(hop_count);
            CREATE INDEX IF NOT EXISTS idx_triangles_pair_ab ON triangles(pair_ab);
            CREATE INDEX IF NOT EXISTS idx_triangles_pair_bc ON triangles(pair_bc);
            CREATE INDEX IF NOT EXISTS idx_triangles_pair_ca ON triangles(pair_ca);
        `);
    }

    /**
     * Bulk insert triangles, optimized for large batches (Polygon-scale:
     * millions of rows). Two combined optimizations, both measured against
     * this exact table shape before landing (see project notes — real gains
     * were more modest than index theory alone suggested, roughly 1.7x
     * combined on a 500K-row file-backed benchmark, not a dramatic 5-10x):
     *
     *   1. Drop the 5 secondary indexes before inserting, rebuild them in one
     *      sorted pass after (see dropTriangleIndexes/createTriangleIndexes).
     *      The canonical uniqueness index stays live throughout — needed for
     *      correct de-duplication both within a batch and against pre-existing
     *      rows from a --root partial run (a physical triangle can legitimately
     *      be reachable from more than one flash-loan root).
     *   2. Multi-row batched INSERT (BATCH rows bound per statement instead of
     *      one) to cut JS<->native call overhead. BATCH=75 keeps total bound
     *      params (75*13=975) safely under SQLite's historic 999-variable
     *      limit for portability, even though better-sqlite3's bundled SQLite
     *      defaults much higher in practice.
     *
     * `synchronous` is relaxed for the duration (restored after) — safe
     * because triangles are a fully regenerable cache (see enumerator.ts),
     * so there's no durability risk worth paying for in this window.
     */
    insertTriangles(rows: Array<{
        root_token: string;
        hop_count: number;
        token_a: string;
        token_b: string;
        token_c: string;
        pair_ab: string;
        pair_bc: string;
        pair_ca: string;
        factory_ab: string;
        factory_bc: string;
        factory_ca: string;
        canonical: string;
    }>): number {
        if (rows.length === 0) return 0;
        const now = Math.floor(Date.now() / 1000);

        this.dropTriangleIndexes();

        const BATCH = 75;
        const COLS_PER_ROW = 13;
        const rowPlaceholder = '(' + Array(COLS_PER_ROW).fill('?').join(',') + ')';
        const batchStmt = this.db.prepare(`
            INSERT OR IGNORE INTO triangles (
                root_token, hop_count, token_a, token_b, token_c,
                pair_ab, pair_bc, pair_ca,
                factory_ab, factory_bc, factory_ca,
                canonical, createdAt
            ) VALUES ${Array(BATCH).fill(rowPlaceholder).join(',')}
        `);
        const singleStmt = this.db.prepare(`
            INSERT OR IGNORE INTO triangles (
                root_token, hop_count, token_a, token_b, token_c,
                pair_ab, pair_bc, pair_ca,
                factory_ab, factory_bc, factory_ca,
                canonical, createdAt
            ) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?)
        `);

        const toParams = (r: (typeof rows)[number]) => [
            r.root_token.toLowerCase(), r.hop_count,
            r.token_a.toLowerCase(), r.token_b.toLowerCase(), r.token_c.toLowerCase(),
            r.pair_ab.toLowerCase(), r.pair_bc.toLowerCase(), r.pair_ca.toLowerCase(),
            r.factory_ab.toLowerCase(), r.factory_bc.toLowerCase(), r.factory_ca.toLowerCase(),
            r.canonical, now,
        ];

        const prevSync = this.db.pragma('synchronous', { simple: true }) as number;
        this.db.pragma('synchronous = OFF'); // safe: triangles are fully regenerable, see doc above

        let totalInserted = 0;
        try {
            const tx = this.db.transaction((rs: typeof rows) => {
                let i = 0;
                for (; i + BATCH <= rs.length; i += BATCH) {
                    const flat: Array<string | number> = [];
                    for (let j = i; j < i + BATCH; j++) flat.push(...toParams(rs[j]));
                    const res = batchStmt.run(...flat);
                    totalInserted += res.changes;
                }
                for (; i < rs.length; i++) {
                    const res = singleStmt.run(...toParams(rs[i]));
                    totalInserted += res.changes;
                }
            });
            tx(rows);
        } finally {
            this.db.pragma(`synchronous = ${prevSync}`);
            this.createTriangleIndexes();
        }

        return totalInserted;
    }
}
